### ISSUE TITLE
Pdf to vectorial

### ISSUE THREAD

**Issue by llgcode** [aspose-pdf/Aspose.PDF-for-Java#21]
Hi is there a way to convert a pdf page to vectorial instruction. Tried to use GraphicsDevice but not sure if it's the right solution.

**Comment by codewarior** [comment]
Hi,
Thanks for using Aspose.Pdf for Java. Please note that in order to convert PDF to SVG format which is standard for Vector graphics by W3c. Please try following the instructions specified over [Convert PDF to SVG Format](http://www.aspose.com/docs/display/pdfjava/Convert+PDF+to+SVG+Format). In case you encounter any related issue, please share the resource file, so that we can further look into this matter..

**Comment by llgcode** [comment]
thanks seems great. But for my purpose it would be great to have more control on page rendering, and  having an intermediary representation not svg that is quiet complex but just vectorial instruction provided by a sort of GraphicalHandler.

**Comment by codewarior** [comment]
Hi, 

Thanks for sharing the details.
I am afraid currently Aspose.Pdf for Java does not support the feature to convert PDF page contents to vectorial instruction. However for the sake of correction, I have logged this requirement as PDFJAVA-35921 in our issue tracking system. We will further look into the details of this requirement and will keep you updated on the status of correction. Please be patient and spare us little time. We are sorry for this inconvenience.

**Comment by llgcode** [comment]
thanks @codewarior. Please contact me when it's ok ;-)

**Comment by codewarior** [comment]
Hi,
Once we have updates, we will surely update you. Have a nice time and once again, thanks for using our API's.
